### ISSUE TITLE
Uppdatera owner?

### ISSUE THREAD

**Issue by HenrikGabrielsson** [jwilsson/1DV450_jw222eu#13]
Inget krav, men kanske hade varit bra om man kunde låta användare uppdatera information som password och användarnamn genom API:et? Ta bort sin profil?
Du borde i alla fall se till så att två användare inte kan heta samma sak, eftersom det är svårt att logga in med “Owner 1” när det redan finns 10 användare som heter detta ;)

**Comment by jwilsson** [comment]
Uppdatera och ta bort sin egen användare ska man absolut kunna göra (och nu kan man det). Jag valde också att ta bort de tillhörande badplatserna.

Självklart ska det inte kunna finnas 10 användare som heter "Owner 1", fixat! ;)
