### ISSUE TITLE
Ta bort taggar från en plats

### ISSUE THREAD

**Issue by HenrikGabrielsson** [jwilsson/1DV450_jw222eu#14]
Ska man kunna ta bort taggar från en plats? Med PUT kan man enbart lägga till nya taggar, men man kan inte ångra sig och ta bort några. Detta är inte heller jätteviktigt, men kanske hade varit trevligt. I övrigt fungerar det bra.

**Comment by jwilsson** [comment]
Hmm, jag tror nog inte att man ska kunna det. Taggarna har ingen ägare i dagsläget och det blir nog lite konstigt om vem som helst kan ta bort någons tagg.

Men tack för rapporten!
