### ISSUE TITLE
Validering av email

### ISSUE THREAD

**Issue by jh222xk** [jwilsson/1DV450_jw222eu#16]
Jag tänkte bara nämna det men när jag skapar en användare via rails consolen så behövde jag inte skriva in en riktigt email utan jag skrev råkade bara skriva in "admin" och sedan så kunde jag då inte logga in i application på grund av du använder HTML5-validering där på emailen.

Du validerar uniqueness och presence här: https://github.com/jwilsson/1DV450_jw222eu/blob/master/app/models/user.rb

Men inte att det faktiskt ska vara en email.

Tänkte bara nämna det.

**Comment by jwilsson** [comment]
Jupp, miss av mig.

Ska se över det, tack ska du ha!
