### ISSUE TITLE
Krångligt med git och branches

### ISSUE THREAD

**Issue by jh222xk** [jwilsson/1DV450_jw222eu#17]
Du har lagt olika projekt i olika branches vilket inte är vad git's branches är till för. Jag hade hellre sett projekten i olika repon. 

Dina instruktioner för att få igång klienten är inte heller fullständiga.

Du säger i instruktioner här: https://github.com/jwilsson/1DV450_jw222eu/tree/client
att det bara är att klona repot och sedan tuta och köra.

Jag måste köra en `git checkout client` för att få tillgång till klienten vilket ej nämns i instruktionerna.
När man kör ovanstående kommando så spottas detta ut:

[master] git checkout client
Note: checking out 'client'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 3962fb4... Fixa felaktig länk-Markdown i READMEn

**Comment by jwilsson** [comment]
Du har helt rätt, miss av mig.

I ac6a778212b9b6d531ee0a8b8753b7e4a2395df0 har jag uppdaterat instuktonerna och förhoppningsvis är det tydligare nu.

**Comment by jh222xk** [comment]
:+1:
