### ISSUE TITLE
Instruktioner för att få igång klienten

### ISSUE THREAD

**Issue by jh222xk** [jwilsson/1DV450_jw222eu#18]
Du skriver `Nu ska applikationen vara färdig att använda!`. Men hur använder man den?

Du skriver också: `För att AJAX-requests ska fungera behöver du köra applikationen från exempelvis localhost. Gå till exempelvis http://localhost/1DV450_jw222eu och testkör applikationen därifrån.`

Så om jag går till `http://localhost/1DV450_jw222eu` förväntas applikationen fungera? Vilket den inte kommer göra.

**Comment by jwilsson** [comment]
Jag kan ha varit otydlig i intruktionerna, men jag säger exempelvis. Jag förutsatte (kanske fel av mig) att man förstod att man får peka om sin lokala server dit man har klonat repot alt. klona repot till sin `htdocs` eller motsvarande.

Jag har i ac6a778212b9b6d531ee0a8b8753b7e4a2395df0 försökt förtydliga instuktionerna.

**Comment by jh222xk** [comment]
:+1:
