### ISSUE TITLE
Validering

### ISSUE THREAD

**Issue by th222fa** [jwilsson/1DV450_jw222eu#2]
Det räcker att lösenordet är ett tecken. Tycker du borde lägga in validering på minst sex tecken.
Du har inte heller någon input för att bekräfta lösenordet vilket kan vara bra att ha.

Bra att du använder dig av has_secure_password

**Comment by jwilsson** [comment]
Längden har du helt rätt i, har fixat det.

Får kolla på ett till fält för att bekräfta lösenordet.
