### ISSUE TITLE
$rootScope

### ISSUE THREAD

**Issue by jh222xk** [jwilsson/1DV450_jw222eu#21]
Du använder $rootScope exempelvis här: https://github.com/jwilsson/1DV450_jw222eu/blob/client/app/user/userLoginController.js#L22

Ett tips är att du skulle kunna använda din userService istället för $rootScope.

**Comment by jwilsson** [comment]
Jag använder bland annat den variabelen ( `signedIn`) i menyn (https://github.com/jwilsson/1DV450_jw222eu/blob/client/app/navbar/views/navbar.html#L9) för att visa/dölja rätt knappar beroende på om man är inloggad eller inte. 

Vill inte hålla på med en service där men ska se om jag kan komma på något sätt att lösa det utan `$rootScope` iaf.
