### ISSUE TITLE
får inte migreringen av databasen att fungera

### ISSUE THREAD

**Issue by th222fa** [jwilsson/1DV450_jw222eu#4]
får följande fel när kör rake db:migrate 
TZInfo::DataSourceNotFound: No source of timezone data could be found.
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.

Vet inte om det kanske hänger ihop med att jag kör windows. Har upplevt lite problem med vissa grejer men du kan kanske se över detta och nämna något i installionsguiden.

**Comment by jwilsson** [comment]
Slängde in en rad i min Gemfile. Har du lust att prova gen får du gärna göra det men annars borde det fungera nu.
