### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by th222fa** [jwilsson/1DV450_jw222eu#5]
Har inte kunnat testa admin då jag inte fick databasen att fungera men koden ser bra ut. Dock bör du kanske fundera över listningen av alla användare och deras applikationer. Om du får många användare (vilket kanske inte är aktuellt) så blir det en hel del scrollande för admin. Någon form av paginering eller filtrering hade varit bra.

**Comment by jwilsson** [comment]
Hade faktiskt inte tänkt så mycket på att listningen kan bli lång. Tack för tipset!
