### ISSUE TITLE
Felhantering/validering

### ISSUE THREAD

**Issue by HenrikGabrielsson** [jwilsson/1DV450_jw222eu#8]
Du verkar ha fångat de mesta felen som jag kan komma på att testa med. Valideringen är också bra och genomtänkt. Det enda jag kan hitta är väl om man använder en route som inte finns (Till exempel en DELETE till api/v1/tags/1 eller bara GET api/v1/noRoute/1). Detta gör att man får Rails fula standard-sida skickad till sig vilket man kanske inte väntar sig av ett API. 
Ett generellt felmeddelande för alla routing-fel kanske skulle vara bra.

**Comment by jwilsson** [comment]
Ah, tack ska du ha!
